[patterns.atoms]
pre = "[-_\\.]?(?:alpha|a|beta|b|preview|pre|c|rc)(?:[-_\\.]?[0-9]+)?"
post = "(?:-(?:[0-9]+))|(?:(?:[-_\\.]?(?:post|rev|r))(?:[-_\\.]?(?:[0-9]+))?)"
dev = "[-_\\.]?dev(?:[-_\\.]?[0-9]+)?"

[patterns.forms]
qual = "(?P<pre>{pre})?(?P<post>{post})?(?P<dev>{dev})?"

[phases]
alpha = "a"
a = "a"
beta = "b"
b = "b"
preview = "rc"
pre = "rc"
c = "rc"
rc = "rc"
