[errors]
deformat = "No common format specifier for {oxford}!"
format = "Invalid format specifier {spec} for type {Self}!"
setter = "Invalid value {value} of type {Value} for {Self}.{func}!"

[inactive-specs]
a_f = [
    "",
    "A",
    "A#",
]
b_f = [
    "",
    "B",
    "B#",
]
rc_f = [
    "",
    "C",
    "C#",
]
post_f = [
    "",
    "-",
    "R",
    "-#",
    "R#",
]
dev_f = [
    "",
    "DEV",
    "DEV#",
]

[patterns]
basev_f = "V?"
epoch_f = "\\#*"
release_f = "[\\#\\.]*"
base_f = "{basev_f}({epoch_f}!)?{release_f}"
a_f = "[-_\\.]?(ALPHA|A)[-_\\.]?\\#*"
b_f = "[-_\\.]?(BETA|B)[-_\\.]?\\#*"
rc_f = "[-_\\.]?(PREVIEW|PRE|C|RC)[-_\\.]?\\#*"
pre_f = "{a_f}?{b_f}?{rc_f}?"
post_hyphen_f = "-"
post_head_f = "[-_\\.]?(POST|REV|R)[-_\\.]?"
post_lit_f = "({post_hyphen_f}|{post_head_f})"
post_num_f = "\\#*"
post_f = "({post_lit_f}{post_num_f})?"
dev_head_f = "[-_\\.]?DEV[-_\\.]?"
dev_num_f = "\\#*"
dev_f = "({dev_head_f}{dev_num_f})?"
qual_f = "{pre_f}{post_f}{dev_f}"
basev = "V"
epoch = "[0-9]+"
release = "[0-9]+(\\.[0-9]+)*"
base = "{basev}?({epoch}!)?{release}"
pre_prefix = "[-_\\.]?"
pre_lit = "(ALPHA|A|BETA|B|PREVIEW|PRE|C|RC)"
pre_suffix = "[-_\\.]?"
pre_num = "[0-9]*"
pre = "{pre_prefix}{pre_lit}{pre_suffix}{pre_num}"
post_prefix = "[-_\\.]?"
post_lit = "(POST|REV|R)"
post_suffix = "[-_\\.]?"
post_num = "([0-9]*)"
post_hyphen_num = "-([0-9]+)"
post = "({post_hyphen_num})|(({post_prefix}{post_lit}){post_suffix}{post_num})"
dev_prefix = "[-_\\.]?"
dev_lit = "DEV"
dev_suffix = "[-_\\.]?"
dev_num = "[0-9]*"
dev = "{dev_prefix}{dev_lit}{dev_suffix}{dev_num}"
qual = "{pre}?{post}?{dev}?"
local_splitter = "([-_\\.])"
head = "[-_\\.]?[A-Z]*[-_\\.]?"
num = "[0-9]*"

[phases]
alpha = "a"
a = "a"
beta = "b"
b = "b"
preview = "rc"
pre = "rc"
c = "rc"
rc = "rc"

[qual-restrictor]
absent = "?"
post-aliases = [
    "post",
    "rev",
    "r",
]
re = "(?P<pre>\n    [-_.]?\n    (?P<pre_l>alpha|a|beta|b|preview|pre|c|rc)\n    [-_.]?\n    (?P<pre_n>[0-9]+)?\n)?\n(?P<post>\n    (?:-(?P<post_n1>[0-9]+))\n    |\n    (?:\n        [-_.]?\n        (?P<post_l>post|rev|r)\n        [-_.]?\n        (?P<post_n2>[0-9]+)?\n    )\n)?\n(?P<dev>\n    [-_.]?\n    (?P<dev_l>dev)\n    [-_.]?\n    (?P<dev_n>[0-9]+)?\n)?\n"
sep = [
    "",
    ".",
    "-",
    "_",
]

[qual-restrictor.canon]
a = "a"
b = "b"
rc = "rc"
post = ".post"
dev = ".dev"

[qual-restrictor.inactive]
a = [
    "",
    "A",
    "A#",
]
b = [
    "",
    "B",
    "B#",
]
rc = [
    "",
    "C",
    "C#",
]
post = [
    "",
    "-",
    "R",
    "-#",
    "R#",
]
dev = [
    "",
    "DEV",
    "DEV#",
]

[qual-restrictor.pre-aliases]
a = [
    "alpha",
    "a",
]
b = [
    "beta",
    "b",
]
rc = [
    "preview",
    "pre",
    "c",
    "rc",
]
