[errors]
deformat = "No common format specifier for {oxford}!"
format = "Invalid format specifier {spec} for type {Self}!"
setter = "Invalid value {value} of type {Value} for {Self}.{func}!"

[inactive-specs]
a_f = [
    "",
    "A",
    "A#",
]
b_f = [
    "",
    "B",
    "B#",
]
rc_f = [
    "",
    "C",
    "C#",
]
post_f = [
    "",
    "-",
    "R",
    "-#",
    "R#",
]
dev_f = [
    "",
    "DEV",
    "DEV#",
]

[patterns]
basev = "V"
epoch = "[0-9]+"
epoch_f = "\\#*"
release = "[0-9]+(\\.[0-9]+)*"
release_f = "[\\#\\.]*"
base = "{basev}?({epoch}!)?{release}"
base_f = "{basev}?({epoch_f}!)?{release_f}"
a_prefix = "[-_\\.]?"
a_lit = "(ALPHA|A)"
a_suffix = "[-_\\.]?"
a_num_f = "\\#*"
a_f = "{a_prefix}{a_lit}{a_suffix}{a_num_f}"
b_prefix = "[-_\\.]?"
b_lit = "(BETA|B)"
b_suffix = "[-_\\.]?"
b_num_f = "\\#*"
b_f = "{b_prefix}{b_lit}{b_suffix}{b_num_f}"
rc_prefix = "[-_\\.]?"
rc_lit = "(PREVIEW|PRE|C|RC)"
rc_suffix = "[-_\\.]?"
rc_num_f = "\\#*"
rc_f = "{rc_prefix}{rc_lit}{rc_suffix}{rc_num_f}"
pre_prefix = "[-_\\.]?"
pre_lit = "({a_lit}|{b_lit}|{rc_lit})"
pre_suffix = "[-_\\.]?"
pre_num = "[0-9]*"
pre = "{pre_prefix}{pre_lit}{pre_suffix}{pre_num}"
pre_f = "{a_f}?{b_f}?{rc_f}?"
post_prefix = "[-_\\.]?"
post_lit = "(POST|REV|R)"
post_suffix = "[-_\\.]?"
post_head = "{post_prefix}{post_lit}{post_suffix}"
post_num = "([0-9]*)"
post_impl_num = "([0-9]+)"
post_impl = "-{post_impl_num}"
post = "({post_impl})|(({post_prefix}{post_lit}){post_suffix}{post_num})"
post_hyphen_f = "-"
post_lit_f = "({post_hyphen_f}|{post_head})"
post_num_f = "\\#*"
post_f = "({post_lit_f}{post_num_f})?"
dev_prefix = "[-_\\.]?"
dev_lit = "DEV"
dev_suffix = "[-_\\.]?"
dev_head = "{dev_prefix}{dev_lit}{dev_suffix}"
dev_num = "[0-9]*"
dev_num_f = "\\#*"
dev = "{dev_head}{dev_num}"
dev_f = "({dev_head}{dev_num_f})?"
qual = "{pre}?{post}?{dev}?"
qual_f = "{pre_f}{post_f}{dev_f}"
local_splitter = "([-_\\.])"

[phases]
alpha = "a"
a = "a"
beta = "b"
b = "b"
preview = "rc"
pre = "rc"
c = "rc"
rc = "rc"

[qual-restrictor]
absent = "?"
post-aliases = [
    "post",
    "rev",
    "r",
]
sep = [
    "",
    ".",
    "-",
    "_",
]

[qual-restrictor.canon]
a = "a"
b = "b"
rc = "rc"
post = ".post"
dev = ".dev"

[qual-restrictor.inactive]
a = [
    "",
    "A",
    "A#",
]
b = [
    "",
    "B",
    "B#",
]
rc = [
    "",
    "C",
    "C#",
]
post = [
    "",
    "-",
    "R",
    "-#",
    "R#",
]
dev = [
    "",
    "DEV",
    "DEV#",
]

[qual-restrictor.pre-aliases]
a = [
    "alpha",
    "a",
]
b = [
    "beta",
    "b",
]
rc = [
    "preview",
    "pre",
    "c",
    "rc",
]
