[patterns]
PRE = "[-_\\.]?(?:alpha|a|beta|b|preview|pre|c|rc)(?:[-_\\.]?[0-9]+)?"
POST = "(?:-(?:[0-9]+))|(?:(?:[-_\\.]?(?:post|rev|r))(?:[-_\\.]?(?:[0-9]+))?)"
DEV = "[-_\\.]?dev(?:[-_\\.]?[0-9]+)?"

[phases]
alpha = "a"
a = "a"
beta = "b"
b = "b"
preview = "rc"
pre = "rc"
c = "rc"
rc = "rc"
